#!/usr/bin/env python3
"""
fix_nightly_review.py — Nightly self-review that reads session files and
writes Daily Review/YYYY-MM-DD.md to the Obsidian vault.

Design:
  1. Add _nightly_review() — reads today's session .md files, calls hermes3
     to synthesize a structured review, writes it to vault, sends summary
     via iMessage.
  2. Patch _execute_job() to dispatch 'type: review' jobs to _nightly_review().
  3. Add the Nightly Review job to Jobs.md (type: review, daily at 22:00).

Review structure written to vault:
  # Daily Review — YYYY-MM-DD
  ## What We Worked On
  ## Key Decisions & Insights
  ## Open Threads
  ## Tomorrow
"""
import subprocess, sys, pathlib, datetime

PYTHON = '/Users/alexmcgann/cowork-bridge/.venv/bin/python3'
BRIDGE = '/Users/alexmcgann/cowork-bridge/bridge.py'
VAULT  = '/Users/alexmcgann/Library/Mobile Documents/iCloud~md~obsidian/Documents/LifeOS/AI Archive'

s = open(BRIDGE, encoding='utf-8', errors='replace').read()
orig = s

# ── Guard ─────────────────────────────────────────────────────────────────────
if '_nightly_review' in s:
    print('SKIPPED — nightly review already present')
    sys.exit(0)

# ── Part 1: _nightly_review() function ────────────────────────────────────────
REVIEW_CODE = r'''
# ── Nightly Review ────────────────────────────────────────────────────────────

def _nightly_review():
    """
    Read today's session files, generate a structured daily review via Ollama,
    write to AI Archive/Daily Review/YYYY-MM-DD.md, send summary via iMessage.
    """
    import datetime as _dtnr, pathlib as _plnr
    today_str  = _dtnr.date.today().strftime('%Y-%m-%d')
    vault_path = _plnr.Path(str(SEARCH_DIR))

    # ── Collect today's session files ─────────────────────────────────────────
    search_dirs = [
        _plnr.Path.home() / 'cowork-bridge',
        vault_path,
        vault_path / 'Sessions',
        vault_path / 'AI Archive',
    ]
    session_texts = []
    for d in search_dirs:
        if not d.exists():
            continue
        for f in sorted(d.glob(f'{today_str}*session*.md')):
            try:
                txt = f.read_text(errors='ignore').strip()
                if txt:
                    session_texts.append(f'### {f.name}\n{txt}')
                    print(f'[review] Reading session: {f.name}', flush=True)
            except Exception as _re:
                print(f'[review] Could not read {f}: {_re}', flush=True)

    if not session_texts:
        print(f'[review] No session files found for {today_str} — skipping', flush=True)
        return

    combined = '\n\n---\n\n'.join(session_texts)
    if len(combined) > 9000:
        combined = combined[:9000] + '\n\n[...truncated for length...]'

    # ── Generate review ───────────────────────────────────────────────────────
    review_prompt = (
        f"Today is {today_str}. Here are the conversation sessions from today:\n\n"
        f"{combined}\n\n"
        "Write a structured daily review with EXACTLY these four sections:\n\n"
        "## What We Worked On\n"
        "Bullet points of the main topics, tasks, and conversations from today.\n\n"
        "## Key Decisions & Insights\n"
        "Any conclusions reached, decisions made, or useful things learned.\n\n"
        "## Open Threads\n"
        "Things mentioned but not resolved — questions, follow-ups, loose ends.\n\n"
        "## Tomorrow\n"
        "Specific things worth picking up or following through on tomorrow.\n\n"
        "Be specific and reference actual content from the sessions. "
        "Write in first person from my perspective. Skip sections that have nothing to report."
    )
    sys_prompt = (
        "You are a thoughtful personal assistant writing a structured end-of-day review. "
        "Be specific and grounded in what actually happened — no filler, no generic advice."
    )
    msgs = [
        {'role': 'system', 'content': sys_prompt},
        {'role': 'user',   'content': review_prompt},
    ]
    print(f'[review] Generating daily review for {today_str}...', flush=True)
    result = query_ollama(msgs, model=MODELS.get('archivist', 'hermes3'))

    if not result or not result.strip():
        print('[review] Empty response from model — skipping', flush=True)
        return

    # ── Write to vault ────────────────────────────────────────────────────────
    review_dir = vault_path / 'Daily Review'
    review_dir.mkdir(parents=True, exist_ok=True)
    review_path = review_dir / f'{today_str}.md'

    header = (
        f'# Daily Review — {today_str}\n'
        f'_Auto-generated by bridge at {_dtnr.datetime.now():%H:%M}_\n\n'
    )
    review_path.write_text(header + result.strip())
    print(f'[review] Wrote {review_path}', flush=True)

    # ── Send brief iMessage summary ───────────────────────────────────────────
    summary_msgs = [
        {'role': 'system', 'content': 'Write a brief, friendly 3-4 sentence summary of this daily review for an iMessage notification. Be specific.'},
        {'role': 'user',   'content': result[:2500]},
    ]
    summary = query_ollama(summary_msgs)
    if summary and summary.strip():
        send_imessage(MY_PHONE, f'[Nightly Review — {today_str}]\n\n{summary.strip()}')
        print(f'[review] iMessage summary sent', flush=True)

'''

# Insert before run_shell / query_ollama anchor
anchors = ['\ndef run_shell(', '\ndef execute_code_task(', '\ndef query_ollama(']
inserted = False
for anchor in anchors:
    pos = s.find(anchor)
    if pos != -1:
        s = s[:pos] + REVIEW_CODE + s[pos:]
        print(f'Part 1: _nightly_review() inserted before "{anchor.strip()}"')
        inserted = True
        break

if not inserted:
    print('Part 1 FAILED — no anchor found')
    sys.exit(1)


# ── Part 2: Patch _execute_job to dispatch type='review' ──────────────────────
# Find the existing _execute_job function and insert a type-dispatch at the top
OLD_EXEC = 'def _execute_job(job):\n    import datetime as _dtx\n    name    = job[\'name\']'
NEW_EXEC = (
    'def _execute_job(job):\n'
    '    import datetime as _dtx\n'
    '    # Dispatch special job types\n'
    '    if job.get(\'type\') == \'review\':\n'
    '        _nightly_review()\n'
    '        return\n'
    '    name    = job[\'name\']'
)

if OLD_EXEC not in s:
    # Try to find it with different whitespace
    import re
    m = re.search(r'def _execute_job\(job\):\s+import datetime as _dtx\s+name\s*=\s*job\[.name.\]', s)
    if m:
        s = s[:m.start()] + NEW_EXEC + s[m.end():]
        print('Part 2: _execute_job patched with type dispatch (regex match)')
    else:
        # Show what we have
        idx = s.find('def _execute_job(')
        if idx != -1:
            print(f'Part 2 WARNING: _execute_job found but pattern mismatch. Showing:')
            print(repr(s[idx:idx+200]))
        print('Part 2 SKIPPED — will add type check via alternate method')
        # Fallback: insert at the very start of _execute_job body
        idx = s.find('def _execute_job(job):')
        if idx != -1:
            body_start = s.find('\n', idx) + 1
            ind = '    '
            fallback = (
                f'{ind}# Dispatch special job types\n'
                f'{ind}if job.get(\'type\') == \'review\':\n'
                f'{ind}    _nightly_review()\n'
                f'{ind}    return\n'
            )
            s = s[:body_start] + fallback + s[body_start:]
            print('Part 2: type dispatch inserted via fallback method')
else:
    s = s.replace(OLD_EXEC, NEW_EXEC, 1)
    print('Part 2: _execute_job patched with type dispatch')


# ── Part 3: Update Jobs.md to add Nightly Review job ─────────────────────────
jobs_path = pathlib.Path(VAULT) / 'Jobs.md'
if not jobs_path.exists():
    print('Part 3 SKIPPED — Jobs.md not found (run fix_scheduler.py first)')
else:
    jobs_text = jobs_path.read_text()
    if 'type: review' in jobs_text or 'Nightly Review' in jobs_text:
        print('Part 3 SKIPPED — Nightly Review job already in Jobs.md')
    else:
        # Insert before the ## Disabled section
        REVIEW_JOB = """
### Nightly Review
- **schedule**: daily at 22:00
- **type**: review
- **prompt**: (handled by _nightly_review — reads session files automatically)

"""
        if '## Disabled' in jobs_text:
            jobs_text = jobs_text.replace('## Disabled', REVIEW_JOB + '## Disabled', 1)
        else:
            jobs_text = jobs_text.rstrip() + '\n' + REVIEW_JOB
        jobs_path.write_text(jobs_text)
        print('Part 3: Nightly Review job added to Jobs.md')


# ── Write & validate ──────────────────────────────────────────────────────────
open(BRIDGE, 'w').write(s)
r = subprocess.run([PYTHON, '-m', 'py_compile', BRIDGE], capture_output=True, text=True)
if r.returncode == 0:
    print('\n✅ syntax OK — nightly review installed')
else:
    print(f'\nSYNTAX ERROR:\n{r.stderr}')
    open(BRIDGE, 'w').write(orig)
    print('Restored original — no changes applied')
    sys.exit(1)
